---
- name: Prepare jenkins slave node
  hosts: jenkins-slave
  vars_files:
    - vars.yml

  user: root
  remote_user: master
  sudo: yes


  roles:
   - common
   - git
   - java
   - openvswitch
   - slave
