- name: Intstall 'python-pycurl'
  apt: name=python-pycurl

- name: Add 'ppa:webupd8team/java' repo
  apt_repository: repo='ppa:webupd8team/java'

- name: Run 'apt-get update'
  apt: update_cache=yes

- name: Set debconf seletions for 'oracle-java7-installer'
  shell: echo oracle-java7-installer shared/present-oracle-license-v1-1 boolean true | debconf-set-selections


- name: Set debconf seletions for 'oracle-java7-installer'
  shell: echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections

- name: Install Oracle Java 7
  apt: name=oracle-java7-installer
